### ISSUE TITLE
Template Review Feedback

### ISSUE THREAD

**Issue by delsonting** [jec21/gtm-zones#1]
Appreciate the work to create this template to address a business need for Tag Manager users! 

When reviewing this template, there was concern that using the same name as an existing Tag Manager feature could cause user confusion as there may be differences in implantation and feature set. Please update the title and description for this submission and remove references to "zone" or "zones" and this submissions will be approved. A non-blocking suggestion to describe the problem and how you're implementing this capability to help potential users understand how your approach in the description or documentation. Thanks.

**Comment by jamescottrill** [comment]
Thanks for the feedback, I've removed any reference to Zone or Zone and it's now a "container injector". I intend to create a readme.md when I have capacity, but explanatory documentation is currently available at https://www.conversionworks.co.uk/blog/2019/07/25/zones-what-are-they-good-for/.
